### ISSUE TITLE
User 34 - Use a system user

### ISSUE THREAD

**Issue by EVOTk** [mixman68/pbs-docker#2]
Hello,
This image uses user 34, and it is not very practical in use.
Do you think it's possible to include a GUID / PUID mapping?

**Comment by mixman68** [comment]
Hello, i need to test it

the image was builded by following the proxmox documentation, and i have translated systemd services to supervisord services and in original PBS distribution, the PBS was started on user 34

**Comment by EVOTk** [comment]
Thank you for your reply.
Indeed I understood the principle well, and I am unable to do better unfortunately :(

This forces me to place the backups folder in 774 in order to be able to read it from another container (to save it remotely).

I'm not comfortable with docker imaging let alone mapping a user.

**Comment by mixman68** [comment]
I studied this case, proxmox backup server will throw an error if I start with user != 34.

On proxmox forum, they start this with PUID mapping with LXC, I find how to do this with docker

https://forum.proxmox.com/threads/how-to-run-proxmox-backup-server-as-unprivileged-container.90921/

You can try this : https://docs.docker.com/engine/security/userns-remap/

**Comment by mixman68** [comment]
I have implemented this in last release of 2.x by changing id34 user with PUID and PGID
